version: "3"
services:
  nginx:
    image: nginx:1.17.9
    restart: on-failure:3
    ports: #change if prod
      - 9042:80
        #- 9443:443
    volumes:
      - ./app:/var/www:delegated
      - ./config/default.dev.conf:/etc/nginx/conf.d/default.conf:delegated
      - logs:/var/www/storage/logs
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure:3
    volumes:
      - ./app:/var/www:delegated
    networks:
      - app-network

volumes:
  logs:
    driver: local        

networks:
  app-network:
    driver: bridge
